"""Builds every table and the framework figure of the manuscript from the result files (no number is typed by hand).
Run from the repository root after the pipeline:  python paper/make_paper_assets.py"""
import os, sys, json, glob, re, shutil
import numpy as np
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__))); sys.path.insert(0, ROOT)
RES, EXT, PT, PF = (os.path.join(ROOT, "results_v2"), os.path.join(ROOT, "results_extra"), os.path.join(ROOT, "paper", "tables"), os.path.join(ROOT, "paper", "Figures"))
os.makedirs(PT, exist_ok=True); os.makedirs(PF, exist_ok=True)
J = lambda p: json.load(open(p, encoding="utf-8"))
def ms(v, d=3):
    v = [x for x in v if x is not None]
    return "--" if not v else (f"{np.mean(v):.{d}f}" if len(v) == 1 else f"{np.mean(v):.{d}f}$\\pm${np.std(v, ddof=1):.{d}f}")
def tab(spec, header, rows):
    return "\n".join([f"\\begin{{tabular}}{{{spec}}}", "\\toprule", " & ".join(header) + " \\\\", "\\midrule"] + [" & ".join(r) + " \\\\" for r in rows] + ["\\bottomrule", "\\end{tabular}"]) + "\n"
def save(name, s): open(os.path.join(PT, name + ".tex"), "w", encoding="utf-8").write(s)

# --- reuse blocks already generated by make_tables.py
blocks = {}
tt = open(os.path.join(ROOT, "tables", "tables.tex"), encoding="utf-8").read()
for m in re.finditer(r"% ---- (tab:[\w+]+): [^\n]*\n(\\begin\{tabular\}.*?\\end\{tabular\})", tt, re.S): blocks[m.group(1)] = m.group(2) + "\n"
for lab, name in (("tab:main", "main"), ("tab:ledger", "ledger"), ("tab:dp", "dp"), ("tab:latency", "latency"), ("tab:delay", "delay"), ("tab:contam", "contam"), ("tab:poison", "poison"), ("tab:ablation", "ablation"), ("tab:indist", "indist")):
    if lab in blocks: save(name, blocks[lab])

# --- audit table (three benchmarks)
u, e, eo = (J(os.path.join(EXT, f"{p}_seed0.json"))["audit"] for p in ("unsw", "edge", "edge_noart")); nsl = J(os.path.join(RES, "official_cnn_bilstm_0_-_-_-_selovr.json"))["audit"]
tot = lambda a, k: sum(a["counts"][k].values())
rows = [["NSL-KDD (official split)", f"125,973 + {nsl['test_total']:,}", f"{125973 - tot(nsl, 'fit') - tot(nsl, 'val'):,} (0.01\\%)", f"{nsl['test_exact_overlap_with_train']:,} ({100 * nsl['test_exact_overlap_with_train'] / nsl['test_total']:.1f}\\%)", f"{tot(nsl, 'fit') + tot(nsl, 'val'):,} / {tot(nsl, 'test'):,}"],
        ["UNSW-NB15 (official split)", f"{tot(u, 'fit') + tot(u, 'val') + u['train_duplicates_removed']:,} + {u['test_total']:,}", f"{u['train_duplicates_removed']:,} (42.4\\%)", f"{u['test_exact_overlap_with_train']:,} ({100 * u['test_exact_overlap_with_train'] / u['test_total']:.1f}\\%)", f"{tot(u, 'fit') + tot(u, 'val'):,} / {tot(u, 'test'):,}"],
        ["Edge-IIoTset (random split)", f"{e['corpus_rows']:,}", f"{e['exact_duplicates_removed']:,} ({100 * e['exact_duplicates_removed'] / e['corpus_rows']:.1f}\\%)", "--", f"{tot(e, 'fit') + tot(e, 'val'):,} / {tot(e, 'test'):,}"],
        ["Edge-IIoTset, capture fields removed", f"{eo['corpus_rows']:,}", f"{eo['exact_duplicates_removed']:,} ({100 * eo['exact_duplicates_removed'] / eo['corpus_rows']:.1f}\\%)", "--", f"{tot(eo, 'fit') + tot(eo, 'val'):,} / {tot(eo, 'test'):,}"]]
save("audit", tab("lcccc", ["Benchmark", "Records (train + test)", "Exact duplicates", "Test rows equal to a training row", "Train+val / test after audit"], rows))

# --- site-calibrated decision, three datasets (LightGBM)
nv = J(os.path.join(RES, "novelty.json")); sd = nv["site_decision"]["LightGBM (class-aware MI)"]
def agg(per, key): return [per[s][key] for s in per if per[s].get(key)]
rows = []
def addrows(ds, items):
    for key in ("argmax", "0.02", "0.05", "0.1"):
        w = items(key)
        if w: rows.append([ds, "argmax" if key == "argmax" else f"site, $\\alpha={float(key):.2f}$", ms([x["acc"] for x in w]), ms([x["macro_f1"] for x in w]), ms([x["fpr"] for x in w]), ms([x["attack_det"] for x in w])])
addrows("NSL-KDD", lambda k: agg(sd, k))
for ds in ("unsw", "edge"):
    fs = [J(p) for p in sorted(glob.glob(os.path.join(EXT, f"{ds}_seed*.json")))]
    addrows({"unsw": "UNSW-NB15", "edge": "Edge-IIoTset"}[ds], lambda k, fs=fs: [f["models"]["lgbm"]["site_decision"][k] for f in fs if f["models"]["lgbm"].get("site_decision", {}).get(k)])
save("site", tab("llcccc", ["Dataset", "Decision rule", "Acc.", "Macro-F1", "Benign FPR", "Attack det."], rows))

# --- novelty fusion on NSL-KDD (LightGBM class-aware)
M = "LightGBM (class-aware MI)"; det = nv["detectors"]; rows = []
def row(label, per, mode):
    v = [per[s][mode] for s in per]; rows.append([label, ms([x["macro_f1"] for x in v]), ms([x["fpr"] for x in v]), ms([x["det_seen"] for x in v]), ms([x["det_novel"] for x in v]), ms([x["r2l"] for x in v]), ms([x["u2r"] for x in v])])
row("LightGBM alone", det["iforest"]["0.02"][M], "alone")
row("+ IsolationForest (validation threshold)", det["iforest"]["0.02"][M], "fused")
row("+ Mahalanobis (validation threshold)", det["mahalanobis"]["0.02"][M], "fused")
row("LightGBM alone, commissioning flows excluded", nv["commissioning"]["mahalanobis"][M], "alone")
row("+ Mahalanobis (site, conformal)", nv["commissioning"]["mahalanobis"][M], "fused")
save("novelty", tab("lcccccc", ["Configuration", "Macro-F1", "Benign FPR", "Det. seen", "Det. unseen", "R2L rec.", "U2R rec."], rows))
au = nv["auc"]; save("detectors", tab("lcc", ["Detector", "AUROC (all attacks)", "AUROC (unseen types)"], [[k, ms([v["all"] for v in au[k].values()]), ms([v["novel"] for v in au[k].values()])] for k in ("iforest", "mahalanobis", "iforest+mahalanobis")]))

# --- external leave-one-class-out
rows = []
for ds, nm in (("unsw", "UNSW-NB15"), ("edge", "Edge-IIoTset")):
    fs = [J(p) for p in sorted(glob.glob(os.path.join(EXT, f"{ds}_seed*.json")))]; L = [v for f in fs for v in f.get("loo", {}).values()]
    st = lambda v: v["site"]["mahalanobis"]; g = lambda f: ms([f(v) for v in L])
    rows.append([nm, str(len(L) // max(len(fs), 1)), g(lambda v: st(v)["auroc"]["clf"]), g(lambda v: st(v)["auroc"]["det"]), g(lambda v: st(v)["auroc"]["fused"]),
                 g(lambda v: st(v)["alpha"]["0.05"]["clf"]["det_heldout"]), g(lambda v: st(v)["alpha"]["0.05"]["det"]["det_heldout"]), g(lambda v: st(v)["alpha"]["0.05"]["fused"]["det_heldout"])])
save("loo", tab("lccccccc", ["Dataset", "Classes", "AUROC clf", "AUROC det", "AUROC fused", "Det. clf", "Det. det", "Det. fused"], rows))

# --- trust (selected rows)
tr = J(os.path.join(RES, "trust_main.json")); rows = []
for fl, nm in (("homog", "Homogeneous"), ("hetero", "Heterogeneous")):
    for rule, lab in (("confidence (original Eq.4)", "Confidence-only"), ("beta reputation", "Beta reputation"), ("CUSUM fleet-baseline (classifier)", "CUSUM, fleet baseline"), ("CUSUM device-baseline (+novelty)", "CUSUM, device baseline, +novelty")):
        v = tr[fl][rule]; b, c, s_, n_ = v["benign"], v["compromised"], v["stealth"], v["novel_attack"]
        rows.append([nm, lab, f"{100 * b['ever_quarantined']:.1f}", f"{100 * c['detect']:.0f}", "--" if c["median_delay"] is None else f"{c['median_delay']:.0f}", f"{100 * n_['detect']:.0f}", f"{100 * s_['detect']:.0f}"])
save("trust", tab("llccccc", ["Fleet", "Rule", "False quar. (\\%)", "Detect (\\%)", "Delay", "Unseen type (\\%)", "Stealth 30\\% (\\%)"], rows))

# --- framework figure
import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
plt.rcParams.update({"font.family": "serif", "font.size": 7}); fig, ax = plt.subplots(figsize=(7.16, 2.5)); ax.set_xlim(0, 100); ax.set_ylim(0, 36); ax.axis("off")
def box(x, y, w, h, t, fc):
    ax.add_patch(FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.25,rounding_size=1.2", fc=fc, ec="black", lw=0.7)); ax.text(x + w / 2, y + h / 2, t, ha="center", va="center", fontsize=6.6)
def arr(x1, y1, x2, y2): ax.add_patch(FancyArrowPatch((x1, y1), (x2, y2), arrowstyle="-|>", mutation_scale=7, lw=0.8, color="black"))
box(0.5, 13, 11, 10, "Device flows\n(m per round)", "#e8e8e8")
box(15, 13, 14, 10, "Audited\npreprocessing\n(train-only fit)", "#dbe9f6")
box(33.5, 22, 16.5, 9, "Supervised\nclassifier\n$P(\\mathrm{attack})$", "#fde0c5")
box(33.5, 4, 16.5, 9, "Normal-profile\ndetector\n(Mahalanobis)", "#fde0c5")
box(54.5, 13, 16.5, 10, "Site-calibrated\nconformal\ndecision (window)", "#d5ecd4")
box(76, 13, 12.5, 10, "Device trust\n(CUSUM state\nmachine)", "#f6d5d5")
box(92, 13, 7.5, 10, "Signed\naudit\nledger", "#e6dcf0")
arr(11.7, 18, 14.7, 18); arr(29.3, 20.5, 33.2, 26); arr(29.3, 15.5, 33.2, 8.5); arr(50.3, 26, 54.2, 20.5); arr(50.3, 8.5, 54.2, 15.5); arr(71.3, 18, 75.7, 18); arr(88.8, 18, 91.7, 18)
ax.text(62.7, 29.5, "clean commissioning window\n(benign flows, held out)", ha="center", fontsize=6.2, style="italic"); arr(62.7, 27, 62.7, 23.4)
fig.savefig(os.path.join(PF, "framework.pdf"), bbox_inches="tight"); fig.savefig(os.path.join(PF, "framework.png"), dpi=220, bbox_inches="tight"); plt.close(fig)
for f in ("trust_trajectories", "trust_theory", "per_class_recall", "shap_faithfulness", "dp_tradeoff", "confusion_matrix"):
    for ext in ("pdf", "png"):
        src = os.path.join(ROOT, "figures", f"{f}.{ext}")
        if os.path.exists(src): shutil.copy(src, PF)
print("assets written:", sorted(os.listdir(PT)), "| figures:", sorted(os.listdir(PF)))
